### ISSUE TITLE
Module not found: "PIL", then error when trying to install it with pip

### ISSUE THREAD

**Issue by Austin-540** [MarwariTheHorse/ImageToGreyscaleText#2]
<img width="601" alt="Screenshot 2023-01-01 at 6 41 33 PM" src="https://user-images.githubusercontent.com/105258719/210162108-6e766717-f3a1-4f6b-8431-6142f76666fd.png">
<img width="657" alt="Screenshot 2023-01-01 at 6 42 27 PM" src="https://user-images.githubusercontent.com/105258719/210162110-f2eb4928-40e3-4ebf-a188-7cd1bc784212.png">

I can't figure out how I'm meant to install this. It should probably be added to the readme because google is telling me to install pillow, but that isn't making it work, unless I'm missing something really obvious.

Thanks for your help

**Comment by calebbuening** [comment]
I do remember having this problem when I started on the project, now that you mention it. Try:

`pip3 install pillow`

and let me know if that works for you. 

PIL is an older library apparently, and so it's now packaged for compatability under pillow, the newer package.

**Comment by Austin-540** [comment]
<img width="858" alt="Screenshot 2023-01-02 at 10 14 51 AM" src="https://user-images.githubusercontent.com/105258719/210184787-040789f6-04ec-4b77-bbb5-616681420c9c.png">

Unfortunately that doesn't seem to be changing anything. I've just done some googling and it seems that pillow has had some trouble working on apple M1, and I'm guessing that this is probably caused by that.
